import { Raleway } from "next/font/google";

import "./globals.css";
import Navigation from "./components/Navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head>
        <title>Wsp X Discord</title>
      </head>
      <body
        className={`grid place-content-center h-screen ${raleway.className}`}
      >
        <main className="max-w-sm w-screen border rounded border-black dark:border-white aspect-9/16">
          <Navigation />
          {children}
        </main>
      </body>
    </html>
  );
}
